// <auto-generated />
using System;
using LogApplication.DataAccess.DataAccessLogApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogApplication.DataAccess.Migrations
{
    [DbContext(typeof(LogApplicationDbContext))]
    partial class LogApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogApplication.DataAccess.DataAccessLogApplication.LogApplicationDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("componente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data_entrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("funcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tbl_log_aplicacion", "Seguridad");
                });
#pragma warning restore 612, 618
        }
    }
}
